### ISSUE TITLE
Error location of multi-member errors pointing to wrong location, inconsistent with flow.org/try

### ISSUE THREAD

**Issue by lewisf** [flowtype/flow-for-vscode#194] opened 2017-12-17 23:35 UTC
I'm not sure if there is a great solution for this -- but I'm noticing that the call site of the errors displayed via this plugin is different than what happens in flow.org/try

The errors show up like this in vscode:

![image](https://user-images.githubusercontent.com/588210/34085080-aadc75a6-e33f-11e7-9bb3-a0894f46bf19.png)

Where as the errors show up where I'm doing a type check in flow.org/try show up on the type cast expressions themselves:
![image](https://user-images.githubusercontent.com/588210/34085095-011eef02-e340-11e7-9010-1a5b0165b9b5.png)

[Link to the flow.org/try here](https://flow.org/try/#0FAEwpgxgNghgTmABNGBnViCKASACnAewFsBLVMAHgCUA+RAb2EUQBcALMAOwoFUaAKCDChQARjAgBrAFyJ+VAJSIAvHR4LZOfMTKVsAYWFQKWwqXIheNADSI+NANzAAvsFCRYCVgE8ADklMdCwoAQTplRAomRAA1YQBXMFkQ62jtczAQOKhEzTwzXQpsxJpgAV9ZdN0shKQAH1japVVGnLAndxQvFj8kHk4AdzgYXwBJADMAOTBMzIoAFXDEAyMTfKC5xdtFp3AupHH4zggWEgJOLAWBeY0sdYzeQeGxqZnwS0XHaOZv5j-fv6IYAAemBiHmYFQLCwAHIMAAiBCoAhQABukPhwEw-BYcESCmiADp2Fx+N4VHRGICybJRAQUWAYJwCcxnASQWCIVDYQikSj0ah4bIBiR2IgmQQSXAsIhfAVyFj+NjcfiWYhiRxOGSKQxfjTEFC4CROABzNVstyg8GQ6GYViaxAIFjxOCcDAwRBVBXY5V4sAKNUa0nklpUv5Ol0XGFoEDjGFOVmBklakOUvXeWSG41m6JsjpWrm2+1cR1gZ2u92e+VgRW+1VE5Pa0O-COurD8aOoWMwhQJxAW5hBlM6sPMfV0hlM829txAA)

**Steps to reproduce**:

1. Clone reproduction code: https://github.com/lewisf/q-flow-types
2. npm install
3. open up `index.js` in vscode

The error site reported is flow.org/try is more helpful. Not sure if this is something that can be solved easily, but reporting an issue due to the inconsistency with the flow.org/try tool.

**Comment by orta** [comment] 2018-01-05 13:51
Realistically this is a dupe of https://github.com/flowtype/flow-for-vscode/issues/39 - not much we can do I'm afraid.

**Comment by Mayank1791989** [comment] 2019-06-07 17:16
Try latest version of plugin.

**Closed by Mayank1791989** 2019-06-07 17:16 UTC
