### ISSUE TITLE
VScode uncaught Error

### ISSUE THREAD

**Issue by Abhishek-Modi-Happyperks** [flowtype/flow-for-vscode#279] opened 2018-10-10 07:25 UTC
- Extension Name: flow-for-vscode
- Extension Version: 0.8.4
- OS Version: Linux x64 4.15.0-36-generic
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1195,
		"activateCallTime": 386,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:javascript"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by Mayank1791989** [comment] 2019-06-07 18:12
Duplicate of #205

**Closed by Mayank1791989** 2019-06-07 18:12 UTC
