### ISSUE TITLE
Property flow.pathToFlow doesn't work

### ISSUE THREAD

**Issue by rucka** [flowtype/flow-for-vscode#41] opened 2016-09-30 18:50 UTC
Hi guys,
I installed last version of flowtype (0.33) as local dependency (npm install flow-bin --save-dev) and I configured the property flow.pathToFlow but when I opened a js file vscode returns the error:
`[Flow] Cannot find flow in PATH. Try to install it by npm install flow-bin -g`

That's my .vscode/settings.json:

``` json
{
    "javascript.validate.enable": false,
    "typescript.validate.enable": false,
    "javascript.validate.syntaxValidation": false,
    "javascript.validate.semanticValidation": false,
    "flow.pathToFlow": "./node_modules/.bin/flow"
}

```

If I installed globally flowtype the extension works fine, but I want setup flowtype as local dependency!
Do you have any suggestion?
Best regards
Gianluca

**Comment by chrisblossom** [comment] 2016-10-01 16:45
Try using a full path instead of a relative one.

For example: ``./node_modules/.bin/flow`` -> ``/Users/user_name/npm_package/node_modules/.bin/flow``

**Comment by fhelwanger** [comment] 2016-10-18 10:02
I think it'd be nice if this extension picked up the local `flow-bin` when available. Then the users won't need to install it globally.

**Comment by jgoux** [comment] 2016-10-19 06:35
@chrisblossom If we use a full path, we'll need to edit this setting for every projects.

I also use purescript's support for vscode and they [allow to point to the local node_module's `.bin` directory as an option](https://github.com/nwolverson/vscode-ide-purescript/commit/04d2a463b1a62fd558a974230f55d4eebd42af10).

I think it would be great to have this option too for flow. :+1:

**Comment by jsynowiec** [comment] 2016-10-30 16:52
This is especially important when working on several projects that don't share the same config version due to changes introduced in the new releases of flow-bin.

**Comment by dgieselaar** [comment] 2016-11-07 20:28
FWIW, for Windows users this works by using `c:\\path\\to\\package\\node_modules\\.bin:flow` (via where.exe pattern matching).

**Comment by WhyEvenTry** [comment] 2016-11-26 20:13
So... I have

`"flow.pathToFlow": "c:\\Users\\WhyEvenTry\\OneDrive\\Projects\\flow\\flow.exe"`

and that is definitely the correct path. Still, all I ever get is

`[Flow] Cannot find flow in PATH. Try...`

**Comment by kumarharsh** [comment] 2016-12-05 06:09
It's useless to have an absolute path in "Path to Flow" setting, as projects can be shared across multiple users, and multiple OS's. Shouldn't [this line](https://github.com/flowtype/flow-for-vscode/blob/f2050696063dfbc063571017576821a442b8dedc/lib/utils/util.js#L10) use something like node's `path.resolve()` to get the flow wherever it is instead?

**Comment by WhyEvenTry** [comment] 2016-12-05 06:36
@kumarharsh Thank you for uselessly telling me that water is wet. The issue is that it doesn't work, not if you think it is a good practice.

**Comment by kumarharsh** [comment] 2016-12-05 06:52
@WhyEvenTry please tone down your passive aggressiveness. Perhaps saying "pathtoFlow is redundant" would have been better than "...useless". I'm not trying to point out the obvious that this doesn't work. Even after 2 months+, the workaround (global installation of flow) is the only way to get this to work. As I understand it, the `pathToFlow` setting should be able to point to the **local** installation of flow, not the global one. The global one can be added by the user to the environment path anyways, so in most cases it doesn't matter. If a project needs to be shareable, the ways to have flow are two:
1. Tell *each user* to install flow, then put flow path in global environment.
2. add it to your dev-dependencies and put this flowPath in the shared settings, and that's it. No more thinking or effort required. The local `.flowconfig` can be easily synced with the local flow version, and so on.

**Comment by WhyEvenTry** [comment] 2016-12-05 06:54
> please tone down your passive aggressiveness. 

@kumarharsh It is a REACTION - look at the source. Of course, that would mean to admit the fault lies with YOU... impossible, I know.

**Comment by orta** [comment] 2016-12-05 22:16
@WhyEvenTry also, please consider your tone, I also agree with @kumarharsh that it is not the way I'd like communication to go on this repo.

As an update for everyone, I have an active PR specifically dealing with this issue https://github.com/flowtype/flow-for-vscode/pull/53

**Comment by WhyEvenTry** [comment] 2016-12-05 22:26
@orta I _have_ considered my tone from the start. See my reply above yours!!

> that it is not the way I'd like communication to go on this repo.

I could not agree more! I just wish you would have followed your own suggestion.

**Comment by fhelwanger** [comment] 2016-12-06 10:28
@WhyEvenTry you don't need to react this way, you're just making things worse to everyone. I see your point, but you don't need to be so aggressive about it. Rage produces more rage. You can react and point why you don't agree in a much more productive and clear way if your comments aren't filled with rage.

Anyway... just my 2 cents. I think most people don't want to read this type of discussion.

**Comment by WhyEvenTry** [comment] 2016-12-06 10:55
@fhelwanger I don't need to but I choose to. Just like you chose to reply for no reason at all. **Tip: Take a good look in the mirror.** YOU are the reason I keep replying - your hypocrisy is THE WORST.

**Comment by kumarharsh** [comment] 2016-12-06 13:38
@WhyEvenTry please stop trolling so unashamedly. You even went ahead and created a *fake* account (@LionessLover), just to troll? I think by this time, it is very clear to everyone what you're trying to do.

@orta / @gabelevi can you lock this thread if possible?

**Comment by orta** [comment] 2016-12-06 15:56
Sorry - was travelling.

No problem, this thread can be closed, and locked. My PR is merged which should fix this problem once we ship a deploy to VSCE.

**Closed by orta** 2016-12-06 15:56 UTC

**Comment by gabelevi** [comment] 2016-12-07 20:59
@WhyEvenTry - Here is some advice and a warning. This thread is still locked, so a response is not expected.

# Advice

## Other members of the open source community deserve your respect

It is ok to disagree with other members of the open source community. It is ok to constructively offer criticism. It is not ok to intentionally insult.

## Assume good intent and listen

Do you feel attacked after reading a comment? Try assuming that the author of the comment has good intent and is trying to help you. Then re-read with that in mind.

After reading a comment, do you think the author of the comment is stupid? Try assuming that the author of the comment is not stupid. Then debug the misunderstanding. Maybe they don't understand your point or you don't understand their point. Or maybe you are both talking about different things.

When you feel attacked and get defensive, your mind closes. The comment that made you feel defensive might be making some really good points, but you'll miss them since you're just worried about defending yourself.

## Written or verbal abuse is never appropriate

I saw your abusive comment from yesterday before it was deleted. It was not appropriate and violates general condition 8 of GitHub's [terms of service](https://help.github.com/articles/github-terms-of-service/#g-general-conditions).

# Warning

This is an official warning. If you continue with this behavior we will block you from the flowtype and facebook organizations. If you abuse other users on GitHub, the abuse will be reported to GitHub.

That said, I hope this warning will be heeded and you will continue to open the high quality GitHub issues that we have seen from you in the past.
