### ISSUE TITLE
Extension issue - Cannot get flow server to start

### ISSUE THREAD

**Issue by austintackaberry** [flowtype/flow-for-vscode#342] opened 2019-06-13 05:02 UTC
- Issue Type: `Bug`
- Extension Name: `flow-for-vscode`
- Extension Version: `1.1.3`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1,
		"activateCallTime": 98,
		"activateResolvedTime": 2,
		"activationEvent": "onLanguage:javascript"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot find module './config'"
		},
		{
			"name": "Error",
			"message": "Cannot find module 'log4js'"
		}
	]
}
```

When I try to run command to see status of flow server, I get:
`command 'flow.showStatus' not found`

**Comment by Mayank1791989** [comment] 2019-06-13 12:53
Duplicate of #341

**Closed by Mayank1791989** 2019-06-13 12:53 UTC
