### ISSUE TITLE
UI in VS Code is hard to understand compared to Nuclide

### ISSUE THREAD

**Issue by nonameolsson** [flowtype/flow-for-vscode#111] opened 2017-04-15 20:53 UTC
Hi!
Thanks for the work with this extension! I really like flow!

There is one thing though, which I don't really understand. I have compared how Flow works in Atom vs. Visual Studio Code. 

I think that the Atom(Nuclide) UI is much better and easier to understand. I'll try to illustrate what I mean with the following screenshots with some comments.

**Hovering over an error message**
<img width="730" alt="1 - vscode - onids" src="https://cloud.githubusercontent.com/assets/1493018/25066650/afee6cea-222c-11e7-97b8-9bbd8e794047.png">
<img width="643" alt="1 - atom - onids" src="https://cloud.githubusercontent.com/assets/1493018/25066651/afefb654-222c-11e7-9153-59b9f4ca3558.png">

**Hovering function parameter type refence defined as a type**
<img width="664" alt="2 - vscode - device type" src="https://cloud.githubusercontent.com/assets/1493018/25066666/48994550-222d-11e7-8948-7a65450af8c0.png">
<img width="391" alt="2 - atom - device type" src="https://cloud.githubusercontent.com/assets/1493018/25066667/489a024c-222d-11e7-9c2d-8bdeb86e8359.png">

**Hovering over the function parameter. This is only shown in VS Code**
<img width="714" alt="3 - vscode - device type 2 not on atom" src="https://cloud.githubusercontent.com/assets/1493018/25066673/6ab5c29e-222d-11e7-8e51-18ee6a9dfb36.png">

**Hovering over the object**
<img width="687" alt="4 - vscode - userid device" src="https://cloud.githubusercontent.com/assets/1493018/25066678/8cf6bdd6-222d-11e7-970d-e93072e1c9a1.png">
<img width="421" alt="4 - atom - userid device" src="https://cloud.githubusercontent.com/assets/1493018/25066679/8d1901ac-222d-11e7-8da3-eb7a1ad60462.png">

**Hovering over type defined object variable**
<img width="502" alt="5 - vscode - userid device userid" src="https://cloud.githubusercontent.com/assets/1493018/25066685/a8d29b92-222d-11e7-8ac2-513e2493aa6d.png">
<img width="369" alt="5 - atom - userid device userid" src="https://cloud.githubusercontent.com/assets/1493018/25066684/a8d1e60c-222d-11e7-87a4-645ab219dd61.png">

**This one is different. I'm hovering over the userId property. I think Atom(Nuclide) is clearer**
<img width="649" alt="6 - vscode - full object" src="https://cloud.githubusercontent.com/assets/1493018/25066695/d4fa076e-222d-11e7-91cc-5bb74618a0b9.png">
<img width="514" alt="6 - atom - full object" src="https://cloud.githubusercontent.com/assets/1493018/25066694/d4f9bf02-222d-11e7-90f3-362238bd3870.png">

This is an example of some scenarios in which I think it's easier to understand in Atom(Nuclide). Am I missing any setting in VS Code which would make it better? It feels like in VS Code it is showing multiple stuff on hover, and just not the Flow info. 
Please correct me if I'm wrong. I really would like to help improving this extension, it you think it could be improved by adapting the Atom UI.

**Comment by orta** [comment] 2017-04-16 11:52
Nice issue, but this is basically a dupe of #97 - there's discussion in there, and there is improvements in master for some of this (specifically around JSON formatting), but other parts aren't possible without someone shipping PRs to vscode itself.

**Comment by svipben** [comment] 2017-04-18 20:44
Opened issue here: https://github.com/Microsoft/vscode/issues/24974.

**Closed** 2021-09-19 19:44 UTC
