### ISSUE TITLE
Flow: the running server is the wrong version

### ISSUE THREAD

**Issue by amypellegrini** [flowtype/flow-for-vscode#317] opened 2019-02-26 11:36 UTC
I get this notification in Visual Studio Code, but no further information is provided that would allow me to fix the issue (what server? what version? where is it running? docs?)

I understand that this may be more related to my local configuration, but more information on how to debug/fix this notification would be helpful.

Thanks!

**Comment by Mayank1791989** [comment] 2019-02-26 18:59
@amypellegrini Flow path which this plugin is using is printed in vscode `Output > Flow`, You can use that to debug.

**Comment by Gujie-Novade** [comment] 2019-02-28 06:48
What fixed it for me on Windows 10 was to run:  `npm install --global flow-bin`
And update the version at the bottom of the file `.flowconfig`

**Comment by go2rob** [comment] 2019-03-04 07:00
> What fixed it for me on Windows 10 was to run: `npm install --global flow-bin`
> And update the version at the bottom of the file `.flowconfig`

+1 also fixed this way on ubuntu

**Comment by thealjey** [comment] 2019-03-04 07:42
being forced to use a global version of flow is not a solution
you cannot rely on your every project working with the same version

**Comment by orta** [comment] 2019-03-04 19:30
It's likely that you've not seen the option to use the node_modules version: see `flow.useBundledFlow` in the README

**Comment by oshalygin** [comment] 2019-03-04 23:47
Man this is non-trivial to solve.  Installed globally and added to `.flowconfig` and still getting the error.  Any way to see the path of the binary it is using?

**Comment by alexandereneroth** [comment] 2019-03-05 12:34
Changing 

```
"flow.pathToFlow": "${workspaceRoot}/node_modules/.bin/flow"
```
to 

```
"flow.pathToFlow": "${workspaceFolder}/node_modules/.bin/flow",
```

fixed it for me 🤔

**Comment by amypellegrini** [comment] 2019-03-05 12:39
Thanks! The setting `flow.useNPMPackagedFlow` fixed it.

**Comment by amypellegrini** [comment] 2019-03-05 12:43
@oshalygin Can you check the console output (the one integrated to VSC)? You should be able to see the path there as per @Mayank1791989 suggestion.

**Comment by oshalygin** [comment] 2019-03-05 21:27
Thanks @amypellegrini !!  Interestingly enough everything works well today.  I will post back if I see anything but I do have `flow.useNPMPackagedFlow` set and installed it globally.  Today its all roses.

BTW @amypellegrini  thanks for all the work on this project/extension.  Sometimes report issues the wrong way which can be pretty annoying.  I just want to say that we are all here to help the project improve and if I find what the issue is I'd be honored to put together a PR :) 

🚀

**Comment by Mayank1791989** [comment] 2019-03-16 06:26
@oshalygin @go2rob @amypellegrini @thealjey If your project has local flow-bin dependency then there is no need to install flow-bin globally, only set config `flow.useNPMPackagedFlow: true` that will be enough. 
Also you can hover over the flow status bar widget or open flow output panel to find the flow path this plugin is using (Note: you will need plugin version `1.1.0` for this)

The current flow-bin resolution behaviour
1) `useNPMPackagedFlow` (default: false): will try to find locally (if failed or value false then will go to next).
2) `flow.pathToFlow` (default: global flow): Will try this (if failed will go to next).
3) flow bundled with this plugin.

@orta Should we change `useNPMPackagedFlow` default value to true.

**Comment by copperseed** [comment] 2019-05-27 07:08
At the bottom of VS Code (in red) will be the Flow version number. Update the package version in package.json and then `npm / yarn install`

**Comment by Mayank1791989** [comment] 2019-06-08 07:25
Closing as https://github.com/flowtype/flow-for-vscode/issues/317#issuecomment-473504623 answered all the issues. Feel free to reopen issue if you are still facing the issue.

**Closed by Mayank1791989** 2019-06-08 07:25 UTC

**Comment by willisplummer** [comment] 2019-07-12 14:45
@Mayank1791989 I'm still running into this issue regularly.

```
[Info  - 10:40:01 AM - smb-admin-ui/.flowconfig] Found flow using option `useNPMPackagedFlow`
[Info  - 10:40:01 AM - smb-admin-ui/.flowconfig] Using flow '/Users/willis/code/smb-admin-ui/node_modules/flow-bin/flow-osx-v0.90.0/flow' (v0.90.0)
Launching Flow server for /Users/willis/code/smb-admin-ui
Spawned flow server (pid=20225)
Logs will go to /private/tmp/flow/zSUserszSwilliszScodezSsmb-admin-ui.log
Monitor logs will go to /private/tmp/flow/zSUserszSwilliszScodezSsmb-admin-ui.monitor_log
[Info  - 10:40:01 AM] Starting Flow server
```

![image](https://user-images.githubusercontent.com/9433365/61136720-179f3100-a492-11e9-8d46-05e64a6c5870.png)
