### ISSUE TITLE
Flow output crippled

### ISSUE THREAD

**Issue by hmeerlo** [flowtype/flow-for-vscode#232] opened 2018-04-16 07:33 UTC
Since [0.66.0](https://github.com/facebook/flow/releases/tag/v0.66.0) flow outputs a much more helpfull output format which makes it much easier to distinguish where the actual errors are (and the error is even colored in red, in this case the word 'event' on 191):

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/components/Planning/PlanningBars/PlanningWoBar/PlanningWoBar.js:191:5

Cannot resolve name event.

     188│   }
     189│
     190│   onStopDrag(position: string) {
     191│     event.preventDefault();
     192│     const newstate = { dragging: {} };
     193│     newstate.dragging[position] = false;
     194│     this.setState(newstate);
```

It would be great if we can this exact output in the tooltip in vscode. Is this possible?

**Comment by orta** [comment] 2018-04-16 08:26
Vscode will soon be supporting multi line errors, so I’d recommend anyone interested in improving error messages to look at supporting that

**Comment by hmeerlo** [comment] 2018-04-16 08:27
@orta Got a link for the issue?

**Comment by orta** [comment] 2018-04-16 08:45
Afraid not, I’m on a phone

**Comment by hmeerlo** [comment] 2018-04-16 08:49
I did some digging for those interested: https://github.com/Microsoft/vscode/issues/1927

**Comment by Mayank1791989** [comment] 2019-06-07 17:48
Duplicate of #122

**Closed by Mayank1791989** 2019-06-07 17:48 UTC
