### ISSUE TITLE
IntelliSense mixed with word-based suggestions

### ISSUE THREAD

**Issue by micmro** [flowtype/flow-for-vscode#100] opened 2017-03-28 02:29 UTC
First of all thanks for creating this great extension 😄, just one little thing that bugs me a bit:

When using Flow, there are a lot of word-based suggestions mixed with the Flow-based IntelliSense (see screenshot below) which makes exploring richer object structures more tedious. In TypeScript on the contrary VS Code does not show any word-based suggestions.

Is the a reason for showing them and if not is it possible to turn them off?

Besides I noticed in this example that `label` is shown twice.

![screen shot 2017-03-28 at 11 00 46 am](https://cloud.githubusercontent.com/assets/1680390/24385596/dc8d2f60-13a5-11e7-8215-d8a2ad40aed4.png)

TypeScript example:
![screen shot 2017-03-28 at 11 05 05 am](https://cloud.githubusercontent.com/assets/1680390/24386027/4de94926-13a8-11e7-9989-f08971383690.png)

Sample code for `MainNav.jsx` used for screenshot:

```javascript
// @flow

import React, { PureComponent } from 'react';

type DummyType = {
  /** Name for menu item */
  label: string;
  /** Url for link */
  url?: string;
}


class MainNav extends PureComponent {
  props: {
    test: DummyType
  }

  render() {
    const {test} = this.props;

    return (
      <div>
        {test.label}
      </div>
    )
  }
}

export default MainNav
```

Versions:
VS Code: `1.10.2`
flowtype.flow-for-vscode: `0.5.0`

**Comment by orta** [comment] 2017-03-28 08:21
Thanks for the great issue, I'm afraid it's a dupe of https://github.com/flowtype/flow-for-vscode/issues/97

I'm not sure if anyone has specifically explored the "remove the words used in the file" as I wonder if that comes from the default JS implementation. You're welcome to take a stab at seeing if that is feasible.

**Comment by sciolist** [comment] 2017-04-15 18:32
The 'words used in the file' suggestions also comes from TypeScript, so they're both the same issue. I've taken to just deleting the typescript extension folder but that's clearly not an optimal solution.

**Comment by yenbekbay** [comment] 2017-06-09 00:39
I think we can close this now as a new option `javascript.nameSuggestions` was shipped in the latest VSCode version: https://github.com/Microsoft/vscode/commit/4514ddd1807ac3b90e65b98da981ab1a8f59f3a0.

**Comment by orta** [comment] 2017-06-09 13:01
👍 agree

**Closed by orta** 2017-06-09 13:01 UTC
