### ISSUE TITLE
Can't run flow in cmd when VS Code is open in Windows

### ISSUE THREAD

**Issue by edele** [flowtype/flow-for-vscode#260] opened 2018-07-11 05:34 UTC
```
flow is running on a different directory.
server_root: c:\Users\edele\flowtest, client_root: C:\Users\edele\flowtest
```

1. Open VS Code in any project, wait flow to initialize
2. Run `yarn run flow`. It will fail with output:
```
C:\Users\edele\flowtest>yarn run flow
yarn run v1.7.0
$ C:\Users\edele\flowtest\node_modules\.bin\flow
flow is running on a different directory.
server_root: c:\Users\edele\flowtest, client_root: C:\Users\edele\flowtest
error Command failed with exit code 14.
```

I use cmd.exe in Windows 10.
I run flow in cmd to see all errors in a project, not just in open files.

Should it be fixed in flow-for-vscode extension or in flow-bin itself?
Is there a workaround?

**Comment by edele** [comment] 2018-07-11 07:42
Looks like the issue originates in  vscode.TextDocument.uri.fsPath which normalizes drive letter to lowercase according to documentation: https://code.visualstudio.com/docs/extensionAPI/vscode-api

**Comment by edele** [comment] 2018-07-11 16:36
But the issue is not solved though. Does it impact anyone else?

Still thinking on a possible solution.

1. Should we force uppercase drive letter because flow-bin uses uppercase?
2. Should we change the way flow-bin decides if `server_root` and `client_root` are not the same just for Windows? (Windows paths are case-insensitive).

**Comment by ArmorDarks** [comment] 2018-09-14 20:14
Same issue here.

**Comment by MannieJay** [comment] 2018-09-15 21:16
Any workarounds?

**Comment by ArmorDarks** [comment] 2018-09-16 08:59
I think there is none. Paths should be fixed in `flow-for-vscode` itself

**Comment by patchkov** [comment] 2018-09-27 17:58
Same issue here on Windows 10, when I'm using Linux Ubuntu 18.04 is work correct. Anyone did find solution?

**Comment by Nauss** [comment] 2018-11-05 16:36
I have the same issue.
A dirty workaround would be to use the npm script `"flow": "flow stop && flow ."`
It works but the server is restarted **both** when launched from the command line **and** by the vscode plugin.

**Comment by tomdbarker** [comment] 2019-08-31 13:41
For me this was caused by a conflict with the flowtype v1.3.0 VSCode extension.
I gave up in the end and uninstalled the extensions and flow worked as normal :/

**Comment by Mayank1791989** [comment] 2019-08-31 15:12
@tomdbarker What is the exact issue you are facing?

**Comment by tomdbarker** [comment] 2019-08-31 17:18
"flow is running on a different directory"

**Comment by Mayank1791989** [comment] 2019-08-31 17:33
You are using wsl or normal shell?

**Comment by mroch** [comment] 2019-09-03 01:01
thanks @Mayank1791989! i'll fix https://github.com/facebook/flow/issues/6592 so it isn't a problem going forward but will still need your fix for previous versions.

**Comment by Mayank1791989** [comment] 2019-09-03 11:20
@mroch When fixed in flow we can put a version check to conditionally apply the fix.

**Closed** 2019-09-05 09:48 UTC
