### ISSUE TITLE
Very slow codeLoadingTime

### ISSUE THREAD

**Issue by klaytonfaria** [flowtype/flow-for-vscode#197] opened 2018-01-10 21:23 UTC
The extension is too slow, increasing vscode CPU usage (48% in average). Some stats below:

- Extension Name: flow-for-vscode
- Extension Version: 0.7.3
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.20.0-insider

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 4432,
		"activateCallTime": 49,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:javascript"
	}
}
```

**Comment by caub** [comment] 2018-02-03 16:43
see #164

**Comment by orta** [comment] 2018-02-08 14:58
Yeah, calling this a dupe of #164

**Closed by orta** 2018-02-08 14:58 UTC
