### ISSUE TITLE
import type doesn't return real type 

### ISSUE THREAD

**Issue by demkovych** [flowtype/flow-for-vscode#343] opened 2019-06-18 08:59 UTC
I imported type from another file and wanna to see types, but instead got type **any**:

![Screen Shot 2019-06-18 at 10 56 13](https://user-images.githubusercontent.com/43744925/59667935-e34c9380-91b7-11e9-8436-020ac0ef26aa.png)

**app.js**:

```
// @flow
import type { UserType } from '_components_/Users/types/User';
```

**types/User**:
```
// @flow
export type UserType = {
  email: string,
  phone: string
};
```

If I declare type in the same file, everything works. 

Flow version 0.81.0
VSCode version 1.35
version 1.35 version 1.1.3

**.flowconfig**
```
[options]
module.system.node.resolve_dirname=./node_modules
module.system.node.resolve_dirname=./src
module.name_mapper='^_components_/\(.*\)$' -> '<PROJECT_ROOT>/src/components/\1'

[ignore]
<PROJECT_ROOT>/node_modules
```

**Comment by noppa** [comment] 2019-06-18 09:21
What do your vscode user/workspace settings for the extension look like?    
If you try to use the type incorrectly in app.js, like
```javascript
// @flow
import type { UserType } from '_components_/Users/types/User';

const wrong: UserType = { email: 5 }
```
does it give you an error like it should?

**Comment by demkovych** [comment] 2019-06-18 09:35
@noppa the same **any**, only eslint give an error

![Screen Shot 2019-06-18 at 11 35 28](https://user-images.githubusercontent.com/43744925/59671019-3aa13280-91bd-11e9-9824-e02ed01ee967.png)

**Comment by noppa** [comment] 2019-06-18 10:10
You said that the "Users" file is "types/User". Is that correct? Shouldn't it be "Users/types/User" as per your flowconfig?

If the path is correct, seems that either Flow or this extension isn't quite set up right. Can you run `flow check` in the command line? Does running that correctly give you an error about the
```javascript
const wrong: UserType = { email: 5 }
```
Would you happen to have this or a minimal reproducible version of this in a public repo somewhere?

**Comment by demkovych** [comment] 2019-06-18 10:16
The path is correct. I have folder **/Users** and inside i have _index.js_ (where i tried to import type) and _/types/User.js_ (where I declared **User** type).
```
Components
  Users
    types
      User.js
    index.js
```
flow check returned 0 errors. 
Unfortunately i don't have a public repo :(

**Comment by demkovych** [comment] 2019-06-18 10:22
I have created one: https://github.com/demkovych/flow-test

**Comment by Mayank1791989** [comment] 2019-06-18 19:53
@demkovych add `@flow` comment in your files it will work.

**Comment by demkovych** [comment] 2019-06-19 07:58
@Mayank1791989 Validation works but still can't see type object on hover 

![Screen Shot 2019-06-19 at 09 57 55](https://user-images.githubusercontent.com/43744925/59747255-d2178b80-9278-11e9-9752-62859e8eb1be.png)

**Comment by Mayank1791989** [comment] 2019-06-19 15:40
@demkovych It's there `imported UserType` is the hover suggestion by flow and `any` is coming from typescript plugin. You need to disable typescript plugin to hide them else you will always get confused with multiple results (see this https://github.com/flowtype/flow-for-vscode#setup).

**Comment by demkovych** [comment] 2019-06-19 15:50
@Mayank1791989 I tried but doesn't work
![Screen Shot 2019-06-19 at 17 49 12](https://user-images.githubusercontent.com/43744925/59780668-a9b08100-92ba-11e9-9a6f-086647cd77c6.png)

**Comment by Mayank1791989** [comment] 2019-06-19 15:56
It's working `imported UserType` is correct (this is how flow shows imported types it is by design). For more details see https://github.com/flowtype/flow-for-vscode/issues/310.

**Comment by Mayank1791989** [comment] 2019-06-22 07:12
Duplicate of #310

**Closed by Mayank1791989** 2019-06-22 07:12 UTC
