### ISSUE TITLE
cmd + click => go to definition instead go to peek definition

### ISSUE THREAD

**Issue by christiandebarrio** [flowtype/flow-for-vscode#207] opened 2018-02-08 16:33 UTC
I don't know why, but when installing the vs code Flow Language Support extension, doesn't work the vs code behavior to 'go to definition' when I do 'command + click'. Instead, it does the 'peek definition'.

**Comment by orta** [comment] 2018-02-08 19:58
Likely because VS Code got two results for it, and the peek is so you can pick. You'd need to disable the JS/TS one.

**Comment by christiandebarrio** [comment] 2018-02-13 17:59
What do you mean by disabling the JS/TS one? Sorry but I don't know what is it.

**Comment by Grsmto** [comment] 2018-02-20 12:12
That's a duplicate of #204. 
I can confirm this is happening. I don't think there is any settings in VSCode to "disable the JS/TS one" so I'm not sure to understand what's the suggested solution for this.

**Comment by orta** [comment] 2018-02-20 12:17
It’s in the readme, something like JavaScript.validate = false

**Comment by Grsmto** [comment] 2018-02-20 12:25
Ah, yeah I understand what you meant. Well, this is with it already set to false.
Actually after further tests, I don't think this issue is related to flow-for-vscode but more to vscode it self.
@christiandebarrio can you confirm this is working when you have the plugin disabled and not working when it's enabled?

From my tests the plugin doesn't actually really affect the Go to definition.

**Comment by christiandebarrio** [comment] 2018-02-20 12:31
@orta, I have the setup "javascript.validate.enable": false, and it doesn't fix the problem. 

And I can confirm that it works fine when I disable the vs code plugin Flow Language Support extension and doesn't when it's enabled. I've just tested again @Grsmto.

**Comment by orta** [comment] 2018-02-25 13:05
You could try the vscode insider's build and see if https://github.com/flowtype/flow-for-vscode/issues/211 fixes this

**Comment by EugeneZ** [comment] 2018-04-09 21:13
Disabling the built in TypeScript plugin as per #211 fixed this problem for me.

**Comment by diegolaciar** [comment] 2018-05-05 00:12
VSCode config:

```"javascript.validate.enable": false```

In my case disable JS validate wasn't enough.

CMD+ click  was pointing to Typescript definition files.

I realized that VSCode was redirecting to definition files at this location.

```~/Library/caches/typescript```

I opted for **delete the cache folder**, and flow types started to work perfectly with CMD+Click

Cheers

**Comment by mattkrick** [comment] 2018-05-23 13:19
With flow extension disabled:
- goto definition works correctly

With flow extension enabled & typescript builtin enabled:
- goto definition finds 2 results: the import statement and the file i want

With flow extension enabled & typescript builtin disabled:
- goto definition goes to the import statement, which isn't very helpful

i think that confirms that the problem is the flow plugin, right?

**Comment by frednomoon** [comment] 2018-06-08 10:36
@diegolaciar I am having the exact same issue, and as you say say deleting the typescript cache fixes the problem.
HOWEVER typescript keeps re-creating the cache, so the problem comes back.
Do you know a way to disable the cache?

**Comment by diegolaciar** [comment] 2018-06-08 12:00
@fredemmott 
You are right, keeps re-creating the cache. I couldn't find a solution to this issue.
Now I' m on other project without flow.

**Comment by taylorgoolsby** [comment] 2018-11-19 04:36
Disabling Typescript Language Features is not an acceptable solution.
With TS Features disbaled, the peek view does not pop up anymore, but the "navigate to" feature is severly weakened. 

With TS features disabled:
* I can no longer ctrl+click on individual imports and it will nagivate to the specific export statement, i.e. `import {individualImport} from './module'`.
* Any time I ctrl+click or go to definition, it just goes to the top of the module's file.

`flow-for-vscode` isn't really great because it forces you to compromise between two different broken nagivation behaviors: annoying peek popup versus poor navigation.

Are most people using flow just accepting the broken behavior or are they not using vscode?

**Comment by orta** [comment] 2018-11-19 12:55
> Is it possible to prevent flow from providing a destination and only use typescript?

That's an interesting approach, I don't think anyone has tried that. You're welcome to give it a shot in a PR. FWIW, there isn't really anyone actively working on improving flow + vscode support (I make sure this extension continues to work, but I moved to typescript ~2 years ago)  - maybe for more folks this is good enough.

**Comment by taylorgoolsby** [comment] 2018-11-19 19:45
I think flow is great and I like it better than typescript for general typing because it has a more intuitive toolset and produces code which IMO is easier to read than TS. However, I think part of the reason for lack of adoption is vscode's bias toward typescript and vscode's popularity. 

I've moved to atom instead for it's hackability and working flowtype support via the `flow-ide` plugin. However, I would like to come back to vscode since it does seem more lightweight than atom.

I'm unfamiliar with how language features work with vscode, so it might take me some time to look at it, but I'll try when I have time.

**Comment by AVykhrystyuk** [comment] 2018-12-06 19:58
I've just disabled Typescript Language Features and "Go to definition" start working fine,
but looks like VSCode used TS features for things like "Rename Symbol" (renames also all usages in project scope). So now when I disabled ts I cannot use that renaming feature, and I only have option to "Change All Occurrences" which is not the same as it renames locally in file scope:
![image](https://user-images.githubusercontent.com/5488533/49607370-cf250f80-f9a6-11e8-92b1-2734e91577e7.png)

Is there any possibility to provide similar functionality as 'Rename Symbol' but by `flow-for-vscode` extension?

**Comment by piavgh** [comment] 2018-12-07 10:14
@AVykhrystyuk : I think they still didn't find the solution for this.

My temporary solution is  Ctrl/Cmd + Click, then selec the 2nd definition in the popup

**Comment by LouisJS** [comment] 2019-06-18 13:44
Still no accurate solution for this ?

**Comment by mroch** [comment] 2021-09-19 19:49
having both the Flow and TS servers providing results for the same file is always going to result in more than one result, so if you choose not to disable TS then this is working as expected. if you do disable TS and something isn't working as well as before, please file an issue upstream on the facebook/flow repo since these features are almost always implemented in the language server (flow) not the extension (flow-for-vscode).

thanks, all!

**Closed by mroch** 2021-09-19 19:49 UTC
