### ISSUE TITLE
Define a separate language id for flow

### ISSUE THREAD

**Issue by aeschli** [flowtype/flow-for-vscode#222] opened 2018-03-19 10:32 UTC
Flow is an extension to the JavaScript language. Therefore it should define it's own 'flow' language id:
```json
"contributes": {
    "languages": [
      {
        "id": "javascriptflow",
        "aliases": [
          "JavaScript Flow"
        ],
        "extensions": [
          ".js", ".js.flow", 
        ],
        "configuration": "./flow-language-configuration.json"
      }],
    "grammars": [
      {
        "language": "javascriptflow",
        "scopeName": "source.js.flow",
        "path": "./syntaxes/JavaScriptFlow.tmLanguage.json"
      }]
```
This has several advantages:
- When the extension is installed, all '.js' files will be associated with the `javascriptflow` language and no longer with the `javascript` language.
The built-in support for JavaScript (provided through the TypeScript extension) will no longer be activated and the will not interfere anymore (fixes #50).
This works because language associations defined in user extensions win over associations in built-in extensions. 
- The flow extension can contribute it's own TextMate grammar that is better suited for flow (e.g. include the Babel grammar). 
- users can define in the user settings whether `.js` should be associated with `javascriptflow` or with the classic `javascript` mode.
- This helps to build up an 'ecosystem' of other extensions specifically for implemented for flow, e.g. flow specific snippets, formatters...
- That's the much cleaner and user-friendlier alternative to ask them to disable the TypeScript extension and replacing the grammar.
- the same approach has been chosen for [javascriptreact](https://github.com/Microsoft/vscode/blob/94f6bb2c6b9e208c3ddc55765c052575fc98ce65/extensions/javascript/package.json#L13)

As a consequence:
- Extension authors that provide functionality for `javascript` that is also useful for `javascriptflow` have to be convinced to also support the flow language id.

**Comment by jbachhardie** [comment] 2018-03-19 11:00
And what about files that use JSX and Flow? Will we have to define a `javascriptreactflow` id? I'm not sure using separate language identifiers for syntax extensions is sustainable.

**Comment by orta** [comment] 2018-03-19 14:11
This used to be the case, but this project has many users and very few contributors - so it was removed because we'd have had to support a lot of things like you mentioned above. Happy to have people add these kind of things and maintain them though.

**Comment by orta** [comment] 2018-03-19 14:11
Closing as a dupe of https://github.com/flowtype/flow-for-vscode/issues/187

**Closed by orta** 2018-03-19 14:11 UTC
