### ISSUE TITLE
Flow 0.53 displaying errors in editor

### ISSUE THREAD

**Issue by pokorson** [flowtype/flow-for-vscode#158] opened 2017-08-27 12:04 UTC
Hi, I have issue with displaying flow errors in editor.
I'm using `flow@0.53` and `vscode 1.15.1`.
I've created clean project with `create-react-app` and added flow support. After adding simple type checking: 
```
// @flow
import * as React from "react";

type Props = {
  name: string,
};

class App extends React.Component<Props> {
  render() {
    return (
      <div className="App">
      </div>
    );
  }
}
```
and using component like this:
```
ReactDOM.render(<App title="123" />, document.getElementById("root"));
```

that's the error I'm getting by running `flow` in terminal
```
Error: src/index.js:8
  8: const AppComponent = <App title="123" />;
                          ^^^^^^^^^^^^^^^^^^^ React element `App`
 10: class App extends React.Component<Props> {
                                       ^^^^^ property `name`. Property not found in. See: src/App.js:10
  8: const AppComponent = <App title="123" />;
                          ^^^^^^^^^^^^^^^^^^^ props of React element `App`


Found 1 error
```

However in editor it looks like this: 
<img width="1122" alt="zrzut ekranu 2017-08-27 o 14 01 06" src="https://user-images.githubusercontent.com/4233207/29749605-603c72a6-8b30-11e7-84c1-ce3b0d2b4152.png">

So the error coming from incorrect usage of component is displayd on actual component itself

**Comment by KeitIG** [comment] 2017-09-25 14:45
This is a real pain to debug, any news on this?

**Comment by kumarharsh** [comment] 2017-10-05 10:51
+1. I think this PR addressed the issue: https://github.com/flowtype/flow-for-vscode/pull/61, but no idea when it'll be merged.

**Comment by Mayank1791989** [comment] 2019-06-07 17:09
duplicate of issue https://github.com/flowtype/flow-for-vscode/issues/122

**Closed by Mayank1791989** 2019-06-07 17:09 UTC
