### ISSUE TITLE
'Trigger Suggest' inserts function calls when not appropriate

### ISSUE THREAD

**Issue by JulioC** [flowtype/flow-for-vscode#147] opened 2017-07-19 02:18 UTC
When writing a `import { ... } from` statement and auto completing the imported names with Trigger Suggest (ctrl+space on windows), the function args snippet get inserted, even if a function call is not expected there.

I was able to reproduce this behavior by creating a file 'foo.js', which exports a function:

```js
export function fooFn(a: number) {
}
```

And, on another file, writing `import { foo<Trigger Suggest here> } from './foo'`

I hope my description was not that bad. In any case, I'd be happy to giver more information.

**Software**
* flowtype.flow-for-vscode: 0.7.1
* vscode: 1.14.1
* Windows

**Comment by JulioC** [comment] 2017-07-19 02:24
Here are some screenshots. In this case, I don't even start writing the import name, just hit space inside the brackets.

![1](https://user-images.githubusercontent.com/387794/28347864-10a54d60-6c10-11e7-865a-46ad4ac5160e.png)
![2](https://user-images.githubusercontent.com/387794/28347865-10a57312-6c10-11e7-94b2-8e4ed6b4e9f6.png)

The expect behavior would be to insert just the function name, without its signature.

**Comment by WoodyWoodsta** [comment] 2018-03-13 15:44
Still having this issue. If there was an option, I would disable it entirely.

**Comment by Mayank1791989** [comment] 2019-06-08 07:30
Duplicate of #249

**Closed by Mayank1791989** 2019-06-08 07:30 UTC
