### ISSUE TITLE
The flow server doesn't start

### ISSUE THREAD

**Issue by ihortkachuk** [flowtype/flow-for-vscode#224] opened 2018-03-27 11:08 UTC
When I open VSCode the flow server doesn't start. А few days ago everything worked. How to fix this problem?

**Settings**:
```
{
    "javascript.validate.enable": false,
    "flow.enabled": true,
    "flow.useNPMPackagedFlow": true
}
```

**VSCode**: v1.21.1
**flow-bin**: v0.68.0

**Comment by JakubRimal** [comment] 2018-03-27 15:47
Same here. It has started yesterday and I have no idea why (there wasn't any update, right?).

**Comment by JakubRimal** [comment] 2018-03-28 11:49
Ok, now I've realized that the whole extension is not running at all (you can check it by Ctrl + Shift + P > Show Running Extensions) even it is enabled. Do you have any ideas what's wrong?

**Comment by JakubRimal** [comment] 2018-03-28 13:57
Update: In my case it was a global problem of VS Code, some extensions simply didn't run. Sorry for the confusion on this issue.

BTW: I've solved it by complete reinstallation of VS Code (`sudo apt-get purge code`, `rm -rf ~/.config/Code`, `rm -rf ~/.vscode`, then install VS Code and extensions again).

**Comment by TomLingham** [comment] 2018-04-04 08:49
Same problem but simply uninstalling and reinstalling the extension in vscode worked for me. Issue was simply not seeming to work at all. Opening the console in developer tools had a lot of errors related to the flow extensions.

**Comment by alexsasharegan** [comment] 2018-05-22 17:47
I've tried reinstalling the extension, but the flow extension still isn't starting. I really don't want to nuke all of vscode if I don't have to...

**Comment by marknelissen** [comment] 2018-05-30 21:15
It seems that the extension is looking in the wrong place for the "local" flow-bin package. It is looking in the node_modules of the extension instead of the node_modules of the project.

```
[2018-05-30T21:10:03.414Z] [INFO] flow - [unknown]: Flow server in c:\Users\Mark\sandbox\demo-mobile-app
[2018-05-30T21:10:03.590Z] [INFO] flow - Path to Flow: C:\Users\Mark\.vscode\extensions\flowtype.flow-for-vscode-0.8.1\node_modules\.bin\flow.cmd
[2018-05-30T21:10:03.818Z] [INFO] flow - Path to Flow: C:\Users\Mark\.vscode\extensions\flowtype.flow-for-vscode-0.8.1\node_modules\.bin\flow.cmd
[2018-05-30T21:10:03.853Z] [INFO] flow - [not installed]: Flow server in c:\Users\Mark\sandbox\demo-mobile-app
[2018-05-30T21:10:03.890Z] [WARN] flow - 
```

**Comment by GiancarlosIO** [comment] 2018-08-08 20:03
same here!!!

**Comment by matt-block** [comment] 2018-08-26 13:43
I had this issue on a couple of occasions and it was always caused by not having installed the same version of `flow-bin` as declared in the `.flowconfig` of the projects.

**Comment by ntomallen** [comment] 2018-09-13 14:46
@matt-block `yarn global add flow-bin@version` fixed it for me too! Is there a way to get it to point to a local installation instead of the global one? That way I don't have to manually keep track of this everywhere.

**Comment by matt-block** [comment] 2018-09-13 14:55
@ntomallen Yes, in your settings you need to point `flow.pathToFlow` to your workspace node_module in your VS Code settings:

```
// settings.json
{
  "flow.pathToFlow": "${workspaceRoot}/node_modules/.bin/flow",
}
```

`${workspaceRoot}` is a special variable provided by VS Code and it always points to the current project folder. You can find it in the [variables reference](https://code.visualstudio.com/docs/editor/variables-reference) page of the official docs.

I personally prefer to use the local Flow module because this way I can ensure that the installed version and the configured one in `.flowconfig` always match even when I switch projects.

**Comment by JakubRimal** [comment] 2018-09-13 15:05
@matt-block @ntomallen: There is an extra setting for that: `flow.useNPMPackagedFlow`, just set it to true and you are done (no need to change `flow.pathToFlow`).

**Comment by matt-block** [comment] 2018-09-13 15:09
@JakubRimal Thanks! Do you also know what is the behaviour if I have both set up?

- If I have both of them, does the plugin prioritize and use the Npm one?
- If there is no local Flow, will the plugin fallback to using the global one defined with `flow.pathToFlow`?

**Comment by JakubRimal** [comment] 2018-09-13 15:16
@matt-block Not sure, [the documentation](https://github.com/flowtype/flow-for-vscode) doesn't say anything about it. But I would guess that `useNPMPackagedFlow` overrides `pathToFlow`.

**Comment by orta** [comment] 2018-09-13 19:00
Its in the configuration section: https://github.com/flowtype/flow-for-vscode#configuration

Happy to take PRs improving docs 👍

**Comment by patrikniebur** [comment] 2019-03-14 23:44
If someone is experiencing same problem `workspaceRoot` has been deprecated in favor of `workspaceFolder`. So correct path in your settings.json should be:
`"flow.pathToFlow": "${workspaceFolder}/node_modules/.bin/flow",`

https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

**Comment by Mayank1791989** [comment] 2019-03-16 06:38
@patrikniebur The variables link which you shared only works in vscode debugging and task configuration file not in vscode plugins. 

In plugin version `1.1.0` we added support for vscode multi-root workspaces so we also replaces `workspaceRoot` with `workspaceFolder`. Check out the updated configuration docs https://github.com/flowtype/flow-for-vscode#configuration for info.

**Comment by patrikniebur** [comment] 2019-03-18 20:18
Ah sorry for confusion, it's just a reference to deprecation of workspaceRoot by vscode

**Comment by matei-radu** [comment] 2019-10-27 13:24
@Mayank1791989 I think it's safe to close this, right? :wink:

**Closed** 2019-10-27 13:28 UTC

**Comment by nhatanhvl** [comment] 2020-04-08 04:05
You just need to correct the [version] in .flowconfig as flow-bin in package.json so you can restart the server

**Comment by saumar16** [comment] 2020-05-18 17:01
no work 
version
react-native-cli: 2.0.1
react-native: 0.62.2
flow 0.125.1

**Comment by chichilatte** [comment] 2024-11-21 12:57
Nothing was working for me until i turned on `useNPMPackagedFlow ` for both User and Workspace settings.

That is...
* Go to VSCode settings
* Search for `@id:flow.useNPMPackagedFlow @ext:flowtype.flow-for-vscode`
* In User tab ensure the option is checked
* In Workspace tab do the same
